### ISSUE TITLE
老哥我对这个语言中管道很感兴趣，能说一下这个语言设计原想是什么吗？

### ISSUE THREAD

**Issue by WingDust** [kalxd/azelf#1]
老哥我对这个语言中管道很感兴趣，能说一下这个语言设计原想是什么吗？
看文档，对这个语言是做什么，还是不太理解

**Comment by kalxd** [comment]
没什么大的设计原想，只是把其他语言有意思的部分做成语法，从racket/base开始扩展。整个azelf可以看成是一个带有个人风格的util库。
受Haskell影响较深，整体偏向函数式风格，强调柯里化和模式匹配；管道来自于[elixr](https://elixirschool.com/en/lessons/basics/pipe_operator)，只不过加了it关键词。

**Comment by kalxd** [comment]
没啥疑问就关闭了。
